# BulkRegenerateBlogs.ps1
$sourceFolderPath = "C:\Users\LMTest\promotional\mercor-affiliate-blog\src\GeneratedBlogs"

# Path and model for LM Studio
$ModelPath = "C:\Users\LMTest\.lmstudio\bin\lms.exe"
$ModelName = "qwen2.5-coder-1.5b-instruct"

# Category mapping for BlogData_X.md files
$categoryMap = @{
    "BlogData_1.md"  = "creative"
    "BlogData_2.md"  = "tech"
    "BlogData_3.md"  = "tech"
    "BlogData_4.md"  = "law"
    "BlogData_5.md"  = "finance"
    "BlogData_6.md"  = "operations"
    "BlogData_7.md"  = "medicine"
    "BlogData_8.md"  = "sciences"
    "BlogData_9.md"  = "misc"
    "BlogData_10.md" = "finance"
    "BlogData_11.md" = "creative"
}

# --- Verify LM Studio CLI path ---
if (-not (Test-Path $ModelPath)) {
    Write-Host "Error: LM Studio CLI not found at $ModelPath"
    exit 1
}

# --- Markdown regeneration ---
Get-ChildItem -Path $sourceFolderPath -Filter BlogData_*.md | ForEach-Object {
    $filePath = $_.FullName
    $fileName = $_.Name
    $lines = Get-Content $filePath

    $frontMatter = @()
    $body = @()
    $inFrontMatter = $false
    $titleSet = $false
    $descriptionSet = $false
    $headingTitle = $null
    $firstParagraph = $null

    foreach ($line in $lines) {
        if ($line -match '^\s*---\s*$' -and -not $inFrontMatter -and $frontMatter.Count -eq 0) {
            $inFrontMatter = $true
            continue
        }
        elseif ($line -match '^\s*---\s*$' -and $inFrontMatter) {
            $inFrontMatter = $false
            continue
        }

        if ($inFrontMatter) {
            if ($line -match '^\s*[A-Za-z0-9_-]+:\s*.+$') {
                $cleanLine = $line.Trim()
                $frontMatter += $cleanLine
                if ($cleanLine -match '^title:') { $titleSet = $true }
                if ($cleanLine -match '^description:') { $descriptionSet = $true }
            }
        }
        else {
            $body += $line
            if (-not $headingTitle -and $line -match '^#\s+(.+)$') {
                $headingTitle = $matches[1].Trim()
            }
            if (-not $firstParagraph -and $line.Trim().Length -gt 0 `
                    -and -not $line.StartsWith("#") `
                    -and -not $line -match '^(title:|layout:|tags:|categories:)' `
                    -and $line -notmatch '^\s*---\s*$') {
                $firstParagraph = $line.Trim()
            }
        }
    }

    if ($frontMatter.Count -eq 0) {
        $frontMatter = @(
            'title: "Unknown Title"',
            'categories: misc',
            'description: "Autogenerated metadata placeholder"'
        )
        $titleSet = $true
        $descriptionSet = $true
    }

    if (-not $titleSet -and $headingTitle) {
        $frontMatter = @("title: `"$headingTitle`"") + $frontMatter
    }

    if (-not $descriptionSet) {
        if ($firstParagraph) {
            $frontMatter += "description: `"$firstParagraph`""
        }
        elseif ($headingTitle) {
            $frontMatter += "description: `"Insights on $headingTitle`""
        }
        else {
            $frontMatter += "description: `"Autogenerated metadata placeholder`""
        }
    }

    # Auto-assign category
    if ($categoryMap.ContainsKey($fileName)) {
        $frontMatter = $frontMatter | Where-Object { $_ -notmatch '^categories:' }
        $frontMatter += "categories: $($categoryMap[$fileName])"
    }

    # Auto-date from file creation time
    $dateValue = (Get-Item $filePath).CreationTime.ToString("yyyy-MM-ddTHH:mm:ss")
    $frontMatter = $frontMatter | Where-Object { $_ -notmatch '^date:' }
    $frontMatter += "date: $dateValue"

    if ($body.Count -eq 0 -or ($body -join "").Trim().Length -eq 0) {
        $body = @("This is autogenerated placeholder content. Replace with full blog text.")
    }

    $newContent = @("---") + $frontMatter + @("---") + $body
    Set-Content -Path $filePath -Value $newContent

    Write-Host "Regenerated $($_.Name) → Title='$headingTitle' Description='$firstParagraph' Category='$($categoryMap[$fileName])' Date='$dateValue'"
}

# --- JSON regeneration with strict schema + cleaning + fallback ---
# --- JSON regeneration with hard sanitizer ---
for ($i = 1; $i -le 11; $i++) {
    $prompt = @"
You are an expert JSON generator.
Output ONLY valid JSON. Do not include explanations, comments, or text outside the JSON object.

Schema:
{
  "title": "string",
  "category": "string",
  "date": "YYYY-MM-DD HH:mm:ss",
  "content": "string with publish-ready blog text"
}

Blog number: $i
"@

    try {
        $rawOutput = & $ModelPath chat $ModelName -p $prompt

        # --- Hard Sanitization ---
        # Remove ANSI escape codes and non-printable characters
        $rawOutput = $rawOutput -replace '\x1B

\[[0-9;]*[A-Za-z]', ''
        $rawOutput = $rawOutput -replace '[^\x20-\x7E\r\n]', ''

        # Extract only the JSON block between first { and last }
        $startIndex = $rawOutput.IndexOf("{")
        $endIndex   = $rawOutput.LastIndexOf("}")
        if ($startIndex -ge 0 -and $endIndex -gt $startIndex) {
            $jsonText = $rawOutput.Substring($startIndex, ($endIndex - $startIndex + 1))
        } else {
            $jsonText = $rawOutput
        }

        # --- Auto-repair common issues ---
        # Remove trailing commas before } or ]
        $jsonText = $jsonText -replace ',\s*([\}\]

])', '$1'
        # Ensure proper quotes around keys
        $jsonText = $jsonText -replace '(\r?\n)(\s*)([A-Za-z0-9_]+):', '$1$2"$3":'
        # Fix date format if missing time
        $jsonText = $jsonText -replace '"date":\s*"(\d{4}-\d{2}-\d{2})"', '"date": "$1 00:00:00"'

        try {
            $parsed = $jsonText | ConvertFrom-Json -ErrorAction Stop
            Set-Content -Path "$sourceFolderPath\BlogData_$i.json" -Value $jsonText -Encoding UTF8
            Write-Host "Regenerated BlogData_$i.json (sanitized & valid)"
        } catch {
            Write-Host "Error: BlogData_$i.json still invalid, writing fallback."
            $fallback = @{
                title = "Blog Post $i"
                category = if ($categoryMap.ContainsKey("BlogData_$i.md")) { $categoryMap["BlogData_$i.md"] } else { "misc" }
                date = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
                content = "Autogenerated placeholder content."
            } | ConvertTo-Json -Depth 2
            Set-Content -Path "$sourceFolderPath\BlogData_$i.json" -Value $fallback -Encoding UTF8
        }
    } catch {
        Write-Host "Error: Could not execute LM Studio CLI at $ModelPath. Verify installation."
        exit 1
    }
}
