param(
    [string]$sourceFolderPath = "C:\Users\LMTest\promotional\mercor-affiliate-blog\BlogData",
    [string]$markdownFolderPath = "C:\Users\LMTest\promotional\mercor-affiliate-blog\src\GeneratedBlogs"
)

# Ensure folders exist
if (!(Test-Path $sourceFolderPath)) { New-Item -ItemType Directory -Path $sourceFolderPath | Out-Null }
if (!(Test-Path $markdownFolderPath)) { New-Item -ItemType Directory -Path $markdownFolderPath | Out-Null }

# Counters
$validCount = 0
$repairedCount = 0
$fallbackCount = 0

for ($i = 1; $i -le 11; $i++) {
    $body = @{
        model = "lmstudio-community/Qwen2.5-Coder-1.5B-Instruct-GGUF"
        messages = @(
            @{
                role = "system"
                content = "You are an expert JSON generator. Output ONLY valid JSON with keys: title, category, date, content."
            },
            @{
                role = "user"
                content = "Generate BlogData_$i"
            }
        )
        max_tokens = 1024
    } | ConvertTo-Json -Depth 3

    try {
        $response = Invoke-RestMethod -Uri "http://localhost:1234/v1/chat/completions" `
                                      -Method Post `
                                      -ContentType "application/json" `
                                      -Body $body

        $jsonText = $response.choices[0].message.content

        # Hard sanitizer: keep only JSON block
        $startIndex = $jsonText.IndexOf("{")
        $endIndex   = $jsonText.LastIndexOf("}")
        if ($startIndex -ge 0 -and $endIndex -gt $startIndex) {
            $jsonText = $jsonText.Substring($startIndex, ($endIndex - $startIndex + 1))
        }

        $parsed = $jsonText | ConvertFrom-Json -ErrorAction Stop

        # Save JSON
        $jsonPath = Join-Path $sourceFolderPath "BlogData_$i.json"
        Set-Content -Path $jsonPath -Value $jsonText -Encoding UTF8

        # Save Markdown with front matter
        $mdPath = Join-Path $markdownFolderPath "BlogData_$i.md"
        $frontMatter = @"
---
title: "$($parsed.title)"
date: $($parsed.date)
category: $($parsed.category)
---
$($parsed.content)
"@
        Set-Content -Path $mdPath -Value $frontMatter -Encoding UTF8

        Write-Host "BlogData_$i.json and BlogData_$i.md generated successfully"
        $validCount++

    } catch {
        Write-Host "Error: BlogData_$i.json invalid, writing fallback."
        $fallback = @{
            title = "Blog Post $i"
            category = "misc"
            date = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
            content = "Autogenerated placeholder content."
        } | ConvertTo-Json -Depth 2

        $jsonPath = Join-Path $sourceFolderPath "BlogData_$i.json"
        Set-Content -Path $jsonPath -Value $fallback -Encoding UTF8

        $mdPath = Join-Path $markdownFolderPath "BlogData_$i.md"
        $frontMatter = @"
---
title: "Blog Post $i"
date: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
category: misc
---
Autogenerated placeholder content.
"@
        Set-Content -Path $mdPath -Value $frontMatter -Encoding UTF8

        $fallbackCount++
    }
}

# Summary report
Write-Host "Summary:"
Write-Host "Valid files: $validCount"
Write-Host "Fallback files: $fallbackCount"
