# FinalPurgeFrontMatter.ps1
$sourceFolderPath = "C:\Users\LMTest\promotional\mercor-affiliate-blog\src\GeneratedBlogs"

Get-ChildItem -Path $sourceFolderPath -Filter *.md | ForEach-Object {
    $filePath = $_.FullName
    $lines = Get-Content $filePath
    $frontMatter = @()
    $body = @()
    $inFrontMatter = $false

    foreach ($line in $lines) {
        if ($line -match '^\s*---\s*$' -and -not $inFrontMatter -and $frontMatter.Count -eq 0) {
            $inFrontMatter = $true
            continue
        }
        elseif ($line -match '^\s*---\s*$' -and $inFrontMatter) {
            $inFrontMatter = $false
            continue
        }

        if ($inFrontMatter) {
            # Keep only valid YAML key:value lines
            if ($line -match '^\s*[A-Za-z0-9_-]+:\s*.+$') {
                $frontMatter += $line
            }
            # Skip CSS/prose entirely
        }
        else {
            $body += $line
        }
    }

    # Insert defaults if no valid front matter
    if ($frontMatter.Count -eq 0) {
        $frontMatter = @(
            'title: "Unknown Title"',
            'categories: misc',
            'date: 2026-01-01T00:00:00',
            'description: "Autogenerated metadata placeholder"'
        )
    }

    # Rebuild file with clean front matter
    $newContent = @("---") + $frontMatter + @("---") + $body
    Set-Content -Path $filePath -Value $newContent

    Write-Host "Fixed $($_.Name) → strict YAML enforced"
}
