# PurgeAndRestoreFrontMatter.ps1
$sourceFolderPath = "C:\Users\LMTest\promotional\mercor-affiliate-blog\src\GeneratedBlogs"

Get-ChildItem -Path $sourceFolderPath -Filter *.md | ForEach-Object {
    $filePath = $_.FullName
    $lines = Get-Content $filePath
    $frontMatter = @()
    $body = @()
    $inFrontMatter = $false
    $titleSet = $false
    $descriptionSet = $false
    $headingTitle = $null
    $firstParagraph = $null

    foreach ($line in $lines) {
        if ($line -match '^\s*---\s*$' -and -not $inFrontMatter -and $frontMatter.Count -eq 0) {
            $inFrontMatter = $true
            continue
        }
        elseif ($line -match '^\s*---\s*$' -and $inFrontMatter) {
            $inFrontMatter = $false
            continue
        }

        if ($inFrontMatter) {
            # Only keep valid YAML key:value lines, skip blanks
            if ($line -match '^\s*[A-Za-z0-9_-]+:\s*.+$') {
                $frontMatter += $line
                if ($line -match '^title:') { $titleSet = $true }
                if ($line -match '^description:') { $descriptionSet = $true }
            }
        }
        else {
            $body += $line
            # Capture first heading for title
            if (-not $headingTitle -and $line -match '^#\s+(.+)$') {
                $headingTitle = $matches[1].Trim()
            }
            # Capture first valid prose line for description
            if (-not $firstParagraph -and $line.Trim().Length -gt 0 `
                -and -not $line.StartsWith("#") `
                -and -not $line -match '^(title:|layout:|tags:|categories:)' `
                -and $line -notmatch '^\s*---\s*$') {
                $firstParagraph = $line.Trim()
            }
        }
    }

    # Insert defaults if no valid front matter
    if ($frontMatter.Count -eq 0) {
        $frontMatter = @(
            'title: "Unknown Title"',
            'categories: misc',
            'date: 2026-01-01T00:00:00',
            'description: "Autogenerated metadata placeholder"'
        )
        $titleSet = $true
        $descriptionSet = $true
    }

    # If no title in front matter, restore from heading
    if (-not $titleSet -and $headingTitle) {
        $frontMatter = @("title: `"$headingTitle`"") + $frontMatter
    }

    # If no description, restore from first paragraph or fallback
    if (-not $descriptionSet) {
        if ($firstParagraph) {
            $frontMatter = $frontMatter + @("description: `"$firstParagraph`"")
        } else {
            $frontMatter = $frontMatter + @("description: `"Autogenerated metadata placeholder`"")
        }
    }

    # Inject guaranteed body paragraph if none exists
    if ($body.Count -eq 0 -or ($body -join "").Trim().Length -eq 0) {
        $body = @("This is autogenerated placeholder content. Replace with full blog text.")
    }

    $newContent = @("---") + $frontMatter + @("---") + $body
    Set-Content -Path $filePath -Value $newContent

    Write-Host "Fixed $($_.Name) → Title='$headingTitle' Description='$firstParagraph'"
}
