# RestoreTitlesAndDescriptions.ps1
$sourceFolderPath = "C:\Users\LMTest\promotional\mercor-affiliate-blog\src\GeneratedBlogs"

Get-ChildItem -Path $sourceFolderPath -Filter *.md | ForEach-Object {
    $filePath = $_.FullName
    $lines = Get-Content $filePath
    $frontMatter = @()
    $body = @()
    $inFrontMatter = $false
    $titleSet = $false
    $descriptionSet = $false
    $headingTitle = $null
    $firstParagraph = $null

    foreach ($line in $lines) {
        if ($line -match '^\s*---\s*$' -and -not $inFrontMatter -and $frontMatter.Count -eq 0) {
            $inFrontMatter = $true
            continue
        }
        elseif ($line -match '^\s*---\s*$' -and $inFrontMatter) {
            $inFrontMatter = $false
            continue
        }

        if ($inFrontMatter) {
            $frontMatter += $line
            if ($line -match '^title:') { $titleSet = $true }
            if ($line -match '^description:') { $descriptionSet = $true }
        }
        else {
            $body += $line
            # Capture first heading for title
            if (-not $headingTitle -and $line -match '^#\s+(.+)$') {
                $headingTitle = $matches[1].Trim()
            }
            # Capture first valid prose line for description
            if (-not $firstParagraph -and $line.Trim().Length -gt 0 `
                -and -not $line.StartsWith("#") `
                -and -not $line -match '^(title:|layout:|tags:|categories:)' `
                -and $line -notmatch '^\s*---\s*$') {
                $firstParagraph = $line.Trim()
            }
        }
    }

    # If no title in front matter, restore from heading
    if (-not $titleSet -and $headingTitle) {
        $frontMatter = @("title: `"$headingTitle`"") + $frontMatter
    }

    # If no description, restore from first paragraph or fallback
    if (-not $descriptionSet) {
        if ($firstParagraph) {
            $frontMatter = $frontMatter + @("description: `"$firstParagraph`"")
        } else {
            $frontMatter = $frontMatter + @("description: `"Autogenerated metadata placeholder`"")
        }
    }

    $newContent = @("---") + $frontMatter + @("---") + $body
    Set-Content -Path $filePath -Value $newContent

    Write-Host "Restored metadata for $($_.Name): Title='$headingTitle' Description='$firstParagraph'"
}
