# StrictFixFrontMatter.ps1
# Enforces clean YAML front matter by discarding non-YAML lines and inserting defaults

Get-ChildItem "src/GeneratedBlogs" -Filter *.md | ForEach-Object {
    $lines = Get-Content $_.FullName
    $frontMatter = @()
    $body = @()
    $inFrontMatter = $false

    foreach ($line in $lines) {
        # Strip accidental code fences
        if ($line -match '^\s*```') { continue }

        # Detect start of front matter
        if ($line -match '^\s*---\s*$' -and -not $inFrontMatter -and $frontMatter.Count -eq 0) {
            $inFrontMatter = $true
            continue
        }

        # Detect end of front matter
        if ($line -match '^\s*---\s*$' -and $inFrontMatter) {
            $inFrontMatter = $false
            continue
        }

        if ($inFrontMatter) {
            # Only keep valid YAML key:value lines
            if ($line -match '^\s*[A-Za-z0-9_-]+:\s*.+$') {
                # Normalize date formats
                if ($line -match '^date:\s*"?(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}:\d{2})"?$') {
                    $frontMatter += "date: $($matches[1])T$($matches[2])"
                }
                elseif ($line -match '^date:\s*date:\s*(.+)$') {
                    $frontMatter += "date: $($matches[1])"
                }
                else {
                    $frontMatter += $line
                }
            }
            # Skip CSS, prose, or invalid lines
        }
        else {
            $body += $line
        }
    }

    # If no valid front matter found, insert defaults
    if ($frontMatter.Count -eq 0) {
        $frontMatter = @(
            'title: "Unknown Title"',
            'categories: misc',
            'date: 2026-01-01T00:00:00',
            'description: "Autogenerated metadata placeholder"'
        )
    }

    # Build clean file content
    $newLines = @("---") + $frontMatter + @("---") + $body
    $newLines | Set-Content $_.FullName

    Write-Host "Fixed $($_.Name) → strict YAML front matter enforced"
    Write-Host "Corrected front matter for $($_.Name):"
    Write-Host "---"
    $frontMatter | ForEach-Object { Write-Host $_ }
    Write-Host "---"
    Write-Host ""
}
      